name: docker_commander
description: A Docker manager, for local and remote host machins. Works with personalized containers and pre-configured popular containers.
version: 1.0.1
homepage: https://github.com/gmpassos/docker_commander

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  swiss_knife: ^2.5.25
  logging: ^0.11.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
