name: docker_commander
description: A Docker manager for local and remote host machines. Works with personalized containers and pre-configured popular containers, like PostgreSQL, Apache HTTPD and NGINX.
version: 1.0.21
homepage: https://github.com/gmpassos/docker_commander

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  swiss_knife: ^2.5.26
    #path: ../swiss_knife
  mercury_client: ^1.1.19
    #path: ../mercury_client
  logging: ^0.11.4

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.14.4
  pubspec: ^0.1.4
  path: ^1.7.0

executables:
  docker_commander_server:
  docker_commander_console:


